project_id            = "churn-cloud-project-446615"
region                = "asia-south1"
credentials_file      = "credentials.json"
service_account_email = "cicd-sa@churn-cloud-project-446615.iam.gserviceaccount.com"
db_password           = "xVGbknFnb4OypAgr"
mongodb_url           = "mongodb+srv://shreyojitdas95:xVGbknFnb4OypAgr@cluster0.emskq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"